### PR TITLE
[android] uses AppCompat

### PR DESCRIPTION
**Pull request by gsgou**
uses AppCompatAutoCompleteTextView in Android

### CODE REVIEW

**Comment by gsgou** [comment]
[zleao](https://github.com/zleao) Jose all checks are passing now

**Comment by zleao** [comment]
Hello.
Thanks for the fix!

Could you set the version to 3.0.2 and the release notes to something like: 'Fix for InvalidOperationException on Android'

https://github.com/zleao/zoft.MauiExtensions.AutoCompleteEntry/blob/7ae5d79ab251d5c7c7901af0ca3564e32990c8b3/src/Directory.build.props#L14

**Comment by gsgou** [comment]
@zleao version and release notes are updated

**Review by zleao — APPROVED** [review]
Thanks

**Pull request merged**
